-- 254 — Dommy Mommy persona switch + state tables.
--
-- Flips active user from 'therapist' to 'dommy_mommy' and adds two tables
-- the new generators read/write:
--
-- - mommy_mood: daily affect picked by cross-model cron (mommy-mood edge
--   fn). Biases all generators that day (e.g., 'hungry' day → more
--   arousal-touch tasks; 'patient' day → fewer outreach pings; 'aching'
--   day → more chastity reinforcement). Stored once per (user_id, day).
--
-- - mommy_praise_cooldown: prevents arousal-triggered praise outreach
--   from firing more than once per (user_id, hour-bucket). The new
--   mommy-praise edge fn watches arousal_log; without this gate it would
--   spam.
--
-- Persona swap is reversible (just UPDATE user_state SET handler_persona).

-- 1. Flip persona
UPDATE user_state
SET handler_persona = 'dommy_mommy', updated_at = now()
WHERE user_id = '8c69b9c8-34eb-4147-9fec-3c1a5bc74b6f';

-- 2. mommy_mood table
CREATE TABLE IF NOT EXISTS mommy_mood (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL,
  mood_date DATE NOT NULL,
  affect TEXT NOT NULL CHECK (affect IN (
    'hungry', 'delighted', 'watching', 'patient', 'aching',
    'amused', 'possessive', 'indulgent', 'restless'
  )),
  rationale TEXT,
  generated_by TEXT,
  cross_model_summary TEXT,
  arousal_bias_hint TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (user_id, mood_date)
);
CREATE INDEX IF NOT EXISTS idx_mommy_mood_user_date ON mommy_mood (user_id, mood_date DESC);
ALTER TABLE mommy_mood ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS mommy_mood_owner ON mommy_mood;
CREATE POLICY mommy_mood_owner ON mommy_mood FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
DROP POLICY IF EXISTS mommy_mood_service ON mommy_mood;
CREATE POLICY mommy_mood_service ON mommy_mood FOR ALL TO service_role USING (true) WITH CHECK (true);

-- 3. mommy_praise_cooldown
CREATE TABLE IF NOT EXISTS mommy_praise_cooldown (
  user_id UUID NOT NULL,
  hour_bucket TIMESTAMPTZ NOT NULL,
  trigger TEXT NOT NULL,
  last_fired_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (user_id, hour_bucket, trigger)
);
ALTER TABLE mommy_praise_cooldown ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS mommy_praise_cooldown_service ON mommy_praise_cooldown;
CREATE POLICY mommy_praise_cooldown_service ON mommy_praise_cooldown FOR ALL TO service_role USING (true) WITH CHECK (true);

-- 4. arousal_touch_tasks — small Mommy-issued tasks that keep the user
--    in heightened arousal between tentpole tasks. Generated by mommy-touch
--    cron, surfaced on the Today screen.
CREATE TABLE IF NOT EXISTS arousal_touch_tasks (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL,
  prompt TEXT NOT NULL,
  category TEXT NOT NULL CHECK (category IN (
    'edge_then_stop', 'sit_in_panties', 'cold_water', 'voice_beg',
    'mantra_aloud', 'mirror_admission', 'pose_hold', 'whisper_for_mommy'
  )),
  expires_at TIMESTAMPTZ NOT NULL DEFAULT (now() + interval '4 hours'),
  acknowledged_at TIMESTAMPTZ,
  completed_at TIMESTAMPTZ,
  generated_by TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS idx_arousal_touch_user_open
  ON arousal_touch_tasks (user_id, expires_at)
  WHERE completed_at IS NULL;
ALTER TABLE arousal_touch_tasks ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS arousal_touch_tasks_owner ON arousal_touch_tasks;
CREATE POLICY arousal_touch_tasks_owner ON arousal_touch_tasks FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
DROP POLICY IF EXISTS arousal_touch_tasks_service ON arousal_touch_tasks;
CREATE POLICY arousal_touch_tasks_service ON arousal_touch_tasks FOR ALL TO service_role USING (true) WITH CHECK (true);
