-- Migration 348: Community-outreach engine
--
-- Mommy autonomously discovers relevant sissy/feminization communities,
-- drafts journal-style posts in the USER's voice (not Mommy's), and queues
-- them for review. Default = draft + approve. Auto-submit only after the
-- user explicitly opts in per-community (Reddit only; FetLife has no API).
--
-- Tables:
--   outreach_communities       — curated communities Mommy may post in
--   outreach_post_drafts       — drafts pending review / submitted history
--   outreach_engagement_log    — manual engagement (comments etc) the user logs
--   outreach_credentials       — encrypted Reddit OAuth tokens per user
--
-- Hard rules baked in via column defaults and CHECK constraints:
--   - auto_submit_enabled defaults FALSE on every community.
--   - Submit edge function additionally enforces per-community engagement
--     threshold + global rate limits; the column constraints here are the
--     persistence-level guard.

-- ============================================
-- 1. Enums
-- ============================================

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'outreach_platform') THEN
    CREATE TYPE outreach_platform AS ENUM ('reddit', 'fetlife', 'discord');
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'outreach_self_promo_policy') THEN
    CREATE TYPE outreach_self_promo_policy AS ENUM (
      'banned',
      'restricted',
      'allowed_with_engagement',
      'freely_allowed'
    );
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'outreach_post_kind') THEN
    CREATE TYPE outreach_post_kind AS ENUM (
      'journal',
      'discussion',
      'question',
      'project_share'
    );
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'outreach_draft_status') THEN
    CREATE TYPE outreach_draft_status AS ENUM (
      'draft',
      'pending_review',
      'approved',
      'rejected',
      'submitted',
      'failed'
    );
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'outreach_engagement_kind') THEN
    CREATE TYPE outreach_engagement_kind AS ENUM (
      'comment',
      'upvote',
      'view',
      'reply_received'
    );
  END IF;
END $$;

DO $$ BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'outreach_engagement_actor') THEN
    -- 'mommy' here is reserved for engagement Mommy SUGGESTED but the user
    -- still performed manually. The product never auto-comments / auto-upvotes,
    -- so there is no 'bot' actor.
    CREATE TYPE outreach_engagement_actor AS ENUM ('mommy', 'user_manual');
  END IF;
END $$;

-- ============================================
-- 2. outreach_communities
-- ============================================

CREATE TABLE IF NOT EXISTS outreach_communities (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,

  platform outreach_platform NOT NULL,
  -- Reddit: subreddit name without the leading "r/". FetLife: group slug.
  -- Discord: invite code or server snowflake (display only).
  slug TEXT NOT NULL,
  display_name TEXT NOT NULL,

  member_count INTEGER,
  -- Pinned-post / sidebar rules summary, generated by outreach-research.
  posting_rules_summary TEXT,
  self_promo_policy outreach_self_promo_policy NOT NULL DEFAULT 'restricted',
  -- Free-form notes about the community's tone (e.g. "wholesome / journaling
  -- focused, not horny", "explicit allowed, NSFW required").
  tone_notes TEXT,

  -- Cadence: typical days between posts the user should leave between
  -- submissions to this community. Used by the draft generator.
  typical_post_cadence_days INTEGER NOT NULL DEFAULT 7,

  last_researched_at TIMESTAMPTZ,
  last_post_at TIMESTAMPTZ,
  last_engagement_at TIMESTAMPTZ,

  -- Mommy may consider this community for drafting.
  enabled BOOLEAN NOT NULL DEFAULT TRUE,
  -- Approved drafts auto-submit. OFF by default for every community.
  auto_submit_enabled BOOLEAN NOT NULL DEFAULT FALSE,
  -- Required engagement (comments etc) before the first auto-submit.
  min_engagement_before_post INTEGER NOT NULL DEFAULT 5,

  -- Set when a submission returns 403 / "you've been banned".
  banned_at TIMESTAMPTZ,
  banned_reason TEXT,

  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  UNIQUE (user_id, platform, slug)
);

CREATE INDEX IF NOT EXISTS idx_outreach_communities_user_enabled
  ON outreach_communities(user_id, enabled) WHERE banned_at IS NULL;
CREATE INDEX IF NOT EXISTS idx_outreach_communities_research_due
  ON outreach_communities(platform, last_researched_at);

ALTER TABLE outreach_communities ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE tablename = 'outreach_communities'
      AND policyname = 'Users own their data'
  ) THEN
    CREATE POLICY "Users own their data" ON outreach_communities
      FOR ALL USING (auth.uid() = user_id);
  END IF;
END $$;

-- ============================================
-- 3. outreach_post_drafts
-- ============================================

CREATE TABLE IF NOT EXISTS outreach_post_drafts (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  community_id UUID NOT NULL REFERENCES outreach_communities(id) ON DELETE CASCADE,

  kind outreach_post_kind NOT NULL DEFAULT 'journal',

  -- Title (Reddit requires; FetLife/Discord may ignore). Body is markdown
  -- sized to the platform; Reddit accepts markdown directly.
  title TEXT,
  body_markdown TEXT NOT NULL,

  status outreach_draft_status NOT NULL DEFAULT 'pending_review',

  -- For audit. Hands-off if user only approves; populated when user edits.
  user_edits_jsonb JSONB,

  -- Submission outcome.
  submitted_at TIMESTAMPTZ,
  submitted_url TEXT,
  submitted_response_jsonb JSONB,
  submission_error TEXT,

  -- Generation metadata: which generator produced this, what state seeded it.
  generation_context JSONB,

  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_outreach_drafts_user_status
  ON outreach_post_drafts(user_id, status, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_outreach_drafts_community
  ON outreach_post_drafts(community_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_outreach_drafts_submission_window
  ON outreach_post_drafts(user_id, submitted_at DESC)
  WHERE status = 'submitted';

ALTER TABLE outreach_post_drafts ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE tablename = 'outreach_post_drafts'
      AND policyname = 'Users own their data'
  ) THEN
    CREATE POLICY "Users own their data" ON outreach_post_drafts
      FOR ALL USING (auth.uid() = user_id);
  END IF;
END $$;

-- ============================================
-- 4. outreach_engagement_log
-- ============================================

CREATE TABLE IF NOT EXISTS outreach_engagement_log (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  community_id UUID NOT NULL REFERENCES outreach_communities(id) ON DELETE CASCADE,
  draft_id UUID REFERENCES outreach_post_drafts(id) ON DELETE SET NULL,

  kind outreach_engagement_kind NOT NULL,
  -- Optional URL of the comment / post. Free text; not validated.
  target_url TEXT,
  -- Free text: comment body for 'comment', notification text for 'reply_received', etc.
  note TEXT,

  -- Default 'user_manual' — Mommy never engages on behalf of the user.
  -- 'mommy' actor is only allowed when the action is "Mommy SUGGESTED this
  -- comment" — the suggestion was logged, the user followed through manually.
  actor outreach_engagement_actor NOT NULL DEFAULT 'user_manual',

  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_outreach_engagement_user_community
  ON outreach_engagement_log(user_id, community_id, created_at DESC);

ALTER TABLE outreach_engagement_log ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE tablename = 'outreach_engagement_log'
      AND policyname = 'Users own their data'
  ) THEN
    CREATE POLICY "Users own their data" ON outreach_engagement_log
      FOR ALL USING (auth.uid() = user_id);
  END IF;
END $$;

-- ============================================
-- 5. outreach_credentials
-- ============================================
-- Encrypted at rest with the same AES-256-GCM scheme as calendar_credentials.
-- Encryption key lives in OUTREACH_TOKEN_KEY (32 bytes, base64).
-- One row per (user, platform). Today only Reddit is supported; the enum
-- leaves room for FetLife/Discord if they ever ship usable APIs.

CREATE TABLE IF NOT EXISTS outreach_credentials (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  platform outreach_platform NOT NULL,

  username TEXT,

  oauth_token_encrypted TEXT NOT NULL,
  refresh_token_encrypted TEXT NOT NULL,
  expires_at TIMESTAMPTZ NOT NULL,
  scopes TEXT[] NOT NULL DEFAULT '{}',

  connected_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  disconnected_at TIMESTAMPTZ,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  UNIQUE (user_id, platform)
);

CREATE INDEX IF NOT EXISTS idx_outreach_credentials_active
  ON outreach_credentials(user_id, platform) WHERE disconnected_at IS NULL;

ALTER TABLE outreach_credentials ENABLE ROW LEVEL SECURITY;

DO $$ BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies WHERE tablename = 'outreach_credentials'
      AND policyname = 'Users own their data'
  ) THEN
    CREATE POLICY "Users own their data" ON outreach_credentials
      FOR ALL USING (auth.uid() = user_id);
  END IF;
END $$;

NOTIFY pgrst, 'reload schema';
