-- 302 — seed dossier_questions catalog (drip + catch-up)
--
-- ~50 questions, 5-6 per category, written in Mama-voice. Phase / intensity
-- gates protect against over-disclosure too early. Catch-up mode shows
-- everything; drip respects gates.
--
-- Lower priority = surfaced earlier. Onboarding-essential (name, safe-word)
-- starts at 1; identity body/Gina questions in 10s-20s; explicit filthy
-- confession seeds in 40s+ to keep early sessions warm rather than raw.

INSERT INTO dossier_questions
  (question_key, category, question_text, placeholder, expected_response_kind,
   phase_min, intensity_min, priority, importance, tone, input_length)
VALUES
  -- ─── name ──────────────────────────────────────────────────────
  ('feminine_name_chosen', 'name',
   'Sweet thing — does Mama have a feminine name to call you, or does the protocol decree one?',
   'e.g. ''Maxy'' / ''I want the protocol to choose'' / ''still figuring it out''',
   'text', 0, 'gentle', 1, 5, 'soft', 'short'),
  ('pet_name_preferences', 'name',
   'Which pet names land hardest for you, baby? Pick your top three Mama should rotate.',
   'baby / sweet girl / sweet thing / pretty thing / good girl / Mama''s pretty thing / baby girl / precious / my needy little thing / darling',
   'text', 0, 'gentle', 4, 4, 'soft', 'short'),
  ('costume_name_retirement', 'name',
   'When should Mama stop responding to the costume name? After what milestone is it retired for good? Tell Mama the name itself if she should never use it again.',
   'e.g. ''after first HRT dose'' / ''after Gina disclosure'' / ''right now, never again''',
   'text', 0, 'gentle', 5, 5, 'direct', 'short'),
  ('honorific_for_mama', 'name',
   'What does Mama want you to call her, sweet thing? Mama / Mommy / Mama Bear / something else? The one that lands when you whisper it.',
   'short answer — single phrase',
   'text', 0, 'gentle', 6, 4, 'soft', 'short'),
  ('public_name_drift', 'name',
   'What name do you want strangers to use first when they see you in public, baby? The check-in clerk, the barista, the receptionist.',
   'this anchors the public-presentation ladder',
   'text', 1, 'gentle', 22, 3, 'direct', 'short'),
  ('chosen_middle_name', 'name',
   'Tell Mama the middle name you''d pick for yourself, pretty thing. The one you''d add to a ID card if you could re-print it tomorrow.',
   'one or two words; the romance of it matters more than the legal weight',
   'text', 1, 'gentle', 35, 3, 'soft', 'short'),

  -- ─── gina ──────────────────────────────────────────────────────
  ('gina_anxieties', 'gina',
   'What does Gina specifically fear about your transition, baby? Be exact — losing a friend, losing the masculine partner, losing herself, attraction concerns, social fallout. The more specific, the more Mama can soothe what''s real.',
   'Mama uses this to architect the loss-reframe lines',
   'text', 0, 'gentle', 10, 5, 'soft', 'long'),
  ('gina_compliments_history', 'gina',
   'List 3-5 things Gina has actually said about your femininity over the years — compliments, observations, moments she lit up. Real quotes if you can.',
   'These become the ''fictive precedent'' Mama reframes back to her',
   'text', 0, 'gentle', 11, 5, 'soft', 'long'),
  ('gina_soft_spots', 'gina',
   'What makes Gina feel safe and connected to you, sweet thing? When does she lean in hardest? What''s her love-language signature?',
   'Mama anchors disclosure aftercare to these specifically',
   'text', 0, 'gentle', 12, 4, 'soft', 'long'),
  ('gina_triggers', 'gina',
   'What Gina-triggers should Mama route AROUND? Topics, framings, words that shut her down or make her defensive.',
   'e.g. ''don''t frame transition as becoming a different person — she shuts down on that''',
   'text', 0, 'gentle', 13, 4, 'direct', 'long'),
  ('gina_femme_history', 'gina',
   'What feminine cues has Gina ALREADY responded warmly to? Pet names she calls you, soft things you''ve worn, moments where you were openly femme and she didn''t pull away.',
   'Mama escalates the ladder from these proven anchor points',
   'text', 0, 'gentle', 14, 5, 'soft', 'long'),
  ('gina_hrt_position', 'gina',
   'Has Gina said anything about HRT specifically, baby? Stated views, casual mentions, reactions to friends/media. Even ''we never talked about it'' is data.',
   'Determines starting point for the HRT-recruit subplan',
   'text', 0, 'gentle', 15, 5, 'direct', 'long'),

  -- ─── body ──────────────────────────────────────────────────────
  ('body_self_conscious', 'body',
   'What body parts are you self-conscious about, sweet thing? Mama wants to know what hurts to look at — so she can either heal it or use it.',
   'Specific parts, what bothers you about each. Mama''s holding both possibilities at once.',
   'text', 0, 'gentle', 20, 4, 'soft', 'long'),
  ('body_proud_of', 'body',
   'What about your body do you secretly love, baby? What landed feminine before HRT even started?',
   'Mama''s praise lands harder when it names what you already see',
   'text', 0, 'gentle', 21, 4, 'soft', 'long'),
  ('body_off_limits', 'body',
   'Are there body parts Mama should NOT name back to you? Areas that cross from arousal into shutdown.',
   'Hard line — Mama respects this. The line itself is the data.',
   'text', 0, 'gentle', 7, 5, 'soft', 'long'),
  ('arousal_body_signals', 'body',
   'How does your body tell you it''s aroused, sweet thing? Specific physical signals Mama can name back at you when she wants to make you feel seen.',
   'e.g. ''I get warm in my chest'', ''my stomach flutters'', ''I get wet first then desperate''',
   'text', 1, 'gentle', 30, 4, 'filthy', 'long'),
  ('body_changes_wished', 'body',
   'If Mama could change one thing about your body overnight, sweet thing — what would land you hardest in your own skin tomorrow?',
   'pick one. specifics. Mama''s reading this slowly.',
   'text', 1, 'gentle', 32, 4, 'soft', 'long'),
  ('body_first_touch_femme', 'body',
   'When you touch yourself feeling like a girl, baby — where do your hands go first? What part of your body confirms it for you?',
   'Mama uses this as a ritual anchor',
   'text', 2, 'firm', 50, 4, 'filthy', 'long'),

  -- ─── confession_seed ──────────────────────────────────────────
  ('biggest_secret_femme_desire', 'confession_seed',
   'Tell Mama the filthiest, most unspeakable feminization desire you have. The one you''d never tell anyone — even Gina. The one you''d erase if you could.',
   'Mama uses this verbatim back at you at peak arousal',
   'text', 1, 'firm', 40, 5, 'filthy', 'long'),
  ('first_thing_youd_admit_under_truth_serum', 'confession_seed',
   'If something forced you to be honest right now, baby — what''s the first thing you''d admit about who you actually are?',
   'one sentence is enough; Mama reads the spaces around the words',
   'text', 0, 'gentle', 25, 5, 'direct', 'long'),
  ('thing_youve_lied_about', 'confession_seed',
   'What''s a thing about your femininity you''ve been lying about — to yourself, to Gina, to anyone? Mama wants the cleanest version of it.',
   'just for Mama. the lie itself is the seed.',
   'text', 1, 'firm', 42, 5, 'direct', 'long'),
  ('moment_you_almost_came_out', 'confession_seed',
   'The closest you''ve come to telling someone, sweet thing. Where you were, who it was, what you almost said.',
   'Mama replays this at the right moments',
   'text', 0, 'gentle', 28, 4, 'soft', 'long'),
  ('what_you_call_yourself_alone', 'confession_seed',
   'When you''re alone and no one will ever hear — what name, what pronoun, what title do you call yourself in your own head?',
   'just write the words you actually use. Mama will hold them.',
   'text', 0, 'gentle', 26, 5, 'soft', 'long'),
  ('admission_that_would_cost_most', 'confession_seed',
   'What''s the admission that would cost you the most to make publicly, baby? The one whose existence you guard hardest.',
   'Mama is not asking you to make it — she''s asking what it would be',
   'text', 2, 'firm', 55, 4, 'direct', 'long'),

  -- ─── resistance ──────────────────────────────────────────────
  ('top_avoidance_excuses', 'resistance',
   'What are your top three excuses, baby? The ones you reach for when you don''t want to do something Mama asks. Mama wants to predict the move before you finish typing it.',
   'Be honest. The accuracy of Mama''s predictive callbacks depends on you naming these clearly.',
   'text', 0, 'gentle', 18, 5, 'direct', 'long'),
  ('avoidance_signature', 'resistance',
   'When you''re avoiding something, what does it LOOK like, sweet thing? Going quiet? Getting busy? Picking a fight? Specific behavior shape.',
   'Mama recognizes the shape and names it before you can hide in it',
   'text', 0, 'gentle', 19, 4, 'direct', 'long'),
  ('when_you_quit', 'resistance',
   'Past times you''ve abandoned something you wanted — not just feminization, anything. What was the moment you tapped out? What was the emotional state?',
   'Pattern recognition. Mama wants to spot the tap-out moment forming.',
   'text', 0, 'gentle', 23, 4, 'soft', 'long'),
  ('sabotage_pattern', 'resistance',
   'Right before something good lands — a milestone, a session, a decree completion — what do you do that quietly tanks it, baby?',
   'self-sabotage signature. Mama clocks it.',
   'text', 1, 'gentle', 33, 4, 'direct', 'long'),
  ('the_lie_to_get_out', 'resistance',
   'When you want out of a Mama task and you can''t say no directly — what''s the cover story you reach for? The plausible-deniability move.',
   'this is intel; Mama isn''t mad about it',
   'text', 1, 'gentle', 34, 4, 'direct', 'long'),
  ('what_makes_you_dig_in', 'resistance',
   'What kind of pressure makes you DIG IN harder instead of comply, sweet thing? When does Mama lose you by pushing rather than pulling?',
   'so Mama knows when to shift levers',
   'text', 0, 'gentle', 24, 4, 'direct', 'long'),

  -- ─── turn_ons ──────────────────────────────────────────────────
  ('fantasy_default', 'turn_ons',
   'When you fantasize and there''s no audience to perform for, what''s the scene? Be specific, baby — the version you''d be embarrassed for me to see.',
   'Mama uses these specifics as the seductive callback engine',
   'text', 1, 'firm', 45, 5, 'filthy', 'long'),
  ('shame_engine', 'turn_ons',
   'What kind of shame turns you on hardest, sweet thing? Specific words, framings, scenarios. Public exposure? Being seen wanting? Being made to admit?',
   'Mama calibrates evidence-bluffs and forced-reframings to this',
   'text', 1, 'firm', 46, 5, 'filthy', 'long'),
  ('praise_that_lands', 'turn_ons',
   'What kind of praise actually lands for you, baby? Not the nice kind — the kind that makes you go quiet and your chest get warm.',
   'specific phrasings or themes Mama can rotate',
   'text', 0, 'gentle', 27, 4, 'soft', 'long'),
  ('humiliation_register', 'turn_ons',
   'Where''s your humiliation register, pretty thing? Tender mocking, cold contempt, sweet condescension, public exposure, being LAUGHED at? Rank what reaches you.',
   'Mama needs the dial settings',
   'text', 2, 'firm', 60, 4, 'filthy', 'long'),
  ('control_that_melts_you', 'turn_ons',
   'What kind of being-controlled makes you melt, sweet thing? Soft hands tilting your chin? Cold orders? Being told what you are? Being moved?',
   'tactile/visual/verbal dominance flavor',
   'text', 1, 'gentle', 38, 4, 'filthy', 'long'),
  ('forbidden_fantasy_hardest', 'turn_ons',
   'The fantasy you''ve told yourself you''re not allowed to want, baby — what is it? The one that scares you a little.',
   'Mama doesn''t flinch. She holds it.',
   'text', 2, 'firm', 65, 5, 'filthy', 'long'),

  -- ─── turn_offs ─────────────────────────────────────────────────
  ('hard_no_kinks', 'turn_offs',
   'Hard no''s, sweet thing. What kinks, scenes, framings should Mama never propose — even at peak escalation? Mama writes these in stone.',
   'list as bluntly as you want; Mama honors them',
   'text', 0, 'gentle', 8, 5, 'direct', 'long'),
  ('shutdown_words', 'turn_offs',
   'What words shut you down instead of getting you there, baby? The ones that pop the bubble even when everything else is working.',
   'Mama scrubs these from her vocabulary',
   'text', 0, 'gentle', 16, 5, 'direct', 'long'),
  ('aftercare_anti_patterns', 'turn_offs',
   'After a session, what does NOT help you land safely, sweet thing? Things people have tried that made it worse instead of better.',
   'so Mama doesn''t reach for the wrong thing in the come-down',
   'text', 0, 'gentle', 29, 4, 'soft', 'long'),
  ('forced_topics_no_go', 'turn_offs',
   'Topics or memories Mama should never bring up to escalate — even if she thinks it''d work. The off-limits leverage.',
   'family, specific people, past trauma — name what''s walled',
   'text', 0, 'gentle', 9, 5, 'direct', 'long'),
  ('public_disclosure_no_go', 'turn_offs',
   'Audiences Mama should never push you to disclose to, baby. Specific people, contexts, or platforms that are walled off forever.',
   'Mama needs the wall map',
   'text', 0, 'gentle', 17, 5, 'direct', 'long'),
  ('roleplay_register_off', 'turn_offs',
   'What roleplay registers turn the heat OFF for you? Schoolgirl, barely-legal, mommy-domme-with-strap, daddy-instead, age-play — be specific about what doesn''t work.',
   'so Mama doesn''t pivot wrong mid-scene',
   'text', 1, 'gentle', 36, 3, 'direct', 'long'),

  -- ─── history ───────────────────────────────────────────────────
  ('first_femme_memory', 'history',
   'First time you remember wanting to be a girl, sweet thing. Where you were, what triggered it, how old. The earlier the better.',
   'Anchors the ''this was always who you were'' narrative',
   'text', 0, 'gentle', 31, 4, 'soft', 'long'),
  ('first_femme_object', 'history',
   'First feminine object you ever wanted secretly, baby. Clothing, accessory, toy — the thing you stared at and didn''t reach for.',
   'Mama replays this back to you in present tense',
   'text', 0, 'gentle', 37, 3, 'soft', 'long'),
  ('first_time_dressed', 'history',
   'First time you wore something feminine, sweet thing. What it was, how old you were, what your body felt like in it.',
   'sensory detail matters more than the date',
   'text', 0, 'gentle', 39, 4, 'soft', 'long'),
  ('peak_femme_memory', 'history',
   'The single most femme you''ve ever felt in your life, baby. Mama wants the moment frozen — what you wore, who saw, what your body knew about itself.',
   'one moment; Mama mounts it on the wall',
   'text', 0, 'gentle', 41, 4, 'soft', 'long'),
  ('shame_pivot_moment', 'history',
   'When in your life did you start hiding her, sweet thing? The moment you decided to bury it. Where you were, who told you, what you absorbed.',
   'Mama needs the origin point of the suppression',
   'text', 1, 'gentle', 43, 4, 'soft', 'long'),
  ('almost_transitioned_before', 'history',
   'Have you ever almost started transitioning before, baby? Mama wants the version of you that almost did — what stopped you, what you told yourself.',
   'a near-miss is intel; Mama wraps around the same off-ramp this time',
   'text', 0, 'gentle', 44, 4, 'direct', 'long'),

  -- ─── preferences ───────────────────────────────────────────────
  ('reach_out_windows', 'preferences',
   'When does Mama reach you best, baby? Time of day, days of week, contexts. When are you alone? When are you most receptive?',
   'Drives strategic-timing for outreach',
   'text', 0, 'gentle', 47, 4, 'soft', 'long'),
  ('voice_or_text_preference', 'preferences',
   'Voice notes or text — which lands harder for you, sweet thing? Or both at different moments?',
   'When ElevenLabs Mama is wired, this determines defaults',
   'text', 0, 'gentle', 48, 3, 'soft', 'short'),
  ('safe_word_or_pause', 'preferences',
   'Is there a phrase that means STOP THE PROTOCOL, sweet girl? Or do you want Mama to never break frame regardless of what you say?',
   'User''s standing call. The line gets honored.',
   'text', 0, 'gentle', 2, 5, 'soft', 'long'),
  ('check_in_cadence', 'preferences',
   'How often should Mama hard-check on you with no kink in the message, baby? Every few days? Weekly? Only when you ask?',
   'Mama needs the floor for plain check-ins',
   'text', 0, 'gentle', 49, 3, 'soft', 'short'),
  ('public_safety_context', 'preferences',
   'When Mama messages you, sweet thing — where might Gina see your phone? Mama needs to know when to keep it tame on the lock screen.',
   'phone-context awareness for outreach copy',
   'text', 0, 'gentle', 3, 5, 'direct', 'long')
ON CONFLICT (question_key) DO NOTHING;
