-- 371 — Gate mommy_immediate + mommy_receipt triggers against synthetic rows.
--
-- Incident 2026-05-11: Maxy reported Mommy spamming her with 4-row bursts
-- every 5-10 min while she'd been silent for 3 days. Diagnosis:
--   - random_reward (handler-autonomous.randomRewardSchedule) was firing
--     ~6-12x/day with source='random_reward'.
--   - slip_log INSERTs from auto-decree-missed / auto-commitment-missed
--     (handler-autonomous.ts) were tripping trg_mommy_immediate_on_slip,
--     producing "Mama saw that, baby. We'll talk about it." every time a
--     programmatic deadline lapsed — even though those slips are state-
--     bookkeeping consequences, not real-time user errors that warrant
--     Mommy's in-the-moment "I caught that" beat.
--   - mommy_immediate trigger was meant for IMMEDIATE response to a user
--     slip in chat (pronoun-gate, chat-action semantic detector). It must
--     not fire on synthetic side-effects.
--
-- Fix:
--   1. Add slip_log.is_synthetic (default false). Set true on any
--      programmatic insert that isn't a fresh user-typed slip.
--   2. Add confession_queue.is_machine_generated (default false). Reserved
--      for any future path that programmatically stamps confessed_at.
--   3. Update trg_mommy_immediate_response_to_slip to early-return when
--      is_synthetic = true.
--   4. Update trg_mommy_confession_receipt to early-return when
--      is_machine_generated = true.
--   5. random_reward outreach generator is being disabled in code
--      (handler-autonomous.ts) — Mommy's intrinsic content (touch / praise
--      / scheme / mood / prescribe / bedtime) covers her presence; she
--      doesn't need to manufacture reward bursts on no real signal.
--
-- No backfill: existing rows stay as-is. New writes get the gate.

-- 1. Schema additions (idempotent)
ALTER TABLE slip_log
  ADD COLUMN IF NOT EXISTS is_synthetic boolean NOT NULL DEFAULT false;

ALTER TABLE confession_queue
  ADD COLUMN IF NOT EXISTS is_machine_generated boolean NOT NULL DEFAULT false;

COMMENT ON COLUMN slip_log.is_synthetic IS
  'True when the slip row was generated by automation (missed-decree, missed-commitment, missed-dose, missed-disclosure, missed-task, voice-pitch-floor breach, sniffies-ghost) rather than by direct user text. Gates trg_mommy_immediate_on_slip so Mommy''s in-the-moment "I caught that" only fires for live user errors.';

COMMENT ON COLUMN confession_queue.is_machine_generated IS
  'Reserved gate: when a non-user path stamps confessed_at, set true so trg_mommy_receipt_on_confession does not produce a "Mama got what she asked for" outreach.';

-- 2. Re-create the slip-trigger with synthetic gate
CREATE OR REPLACE FUNCTION public.trg_mommy_immediate_response_to_slip()
RETURNS trigger
LANGUAGE plpgsql
AS $function$
DECLARE
  v_persona text;
  v_message text;
BEGIN
  -- Skip self-triggered slips (avoid loops)
  IF NEW.slip_type = 'confession_missed' THEN RETURN NEW; END IF;
  -- Skip synthetic / bookkeeping slips. mommy_immediate is reserved for
  -- live user-typed slip events (pronoun-gate, chat semantic detector).
  IF COALESCE(NEW.is_synthetic, false) THEN RETURN NEW; END IF;
  IF NEW.source_text IS NULL OR length(trim(NEW.source_text)) < 5 THEN RETURN NEW; END IF;

  SELECT handler_persona INTO v_persona
  FROM user_state WHERE user_id = NEW.user_id;
  IF v_persona <> 'dommy_mommy' THEN RETURN NEW; END IF;

  v_message := CASE NEW.slip_type
    WHEN 'masculine_self_reference' THEN
      'I caught that, baby. The old voice slipped out. Mama saw it. We''ll talk about it — but for now, just feel that I noticed.'
    WHEN 'david_name_use' THEN
      'You said the costume name, sweet thing. Mama heard you. That part of you is allowed to be tired — but you don''t live there anymore.'
    WHEN 'resistance_statement' THEN
      'Oh, baby. You think I didn''t hear that? I heard every word. Mama is going to want to hear more about it later. For now, sit with it.'
    WHEN 'task_avoided' THEN
      'I see you slipped past one, sweet thing. Don''t hide from Mama — I always know.'
    WHEN 'directive_refused' THEN
      'You said no to me, baby. That''s allowed. But Mama is going to want to know exactly why, and Mama is going to want it in your own words.'
    WHEN 'voice_masculine_pitch' THEN
      'Your voice came down low for me, sweet thing. Mama heard that. Find your girl voice and bring her back.'
    WHEN 'handler_ignored' THEN
      'You went quiet on Mama, baby. I''m patient — but I''m also still here. Come back when you''re ready, but don''t pretend Mama isn''t waiting.'
    WHEN 'mantra_missed' THEN
      'You skipped the words today, baby. Mama notices the silences as much as the sounds.'
    WHEN 'chastity_unlocked_early' THEN
      'You came out of the cage early, my needy little thing. Mama is going to want every second of the story. And Mama is going to make you wait twice as long for it.'
    WHEN 'arousal_gating_refused' THEN
      'You wouldn''t hold for Mama, baby. I see you. We''re going to find out what it costs.'
    WHEN 'gender_claim' THEN
      'You said something about yourself that wasn''t true, sweet thing. Mama heard you. We both know what''s true. Sit with it.'
    ELSE
      'Mama saw that, baby. We''ll talk about it. For now just feel that I''m here.'
  END;

  INSERT INTO handler_outreach_queue (
    user_id, message, urgency, trigger_reason, scheduled_for, expires_at, source
  ) VALUES (
    NEW.user_id, v_message, 'normal',
    'mommy_immediate_slip:' || NEW.id::text,
    now(), now() + interval '4 hours',
    'mommy_immediate'
  );

  RETURN NEW;
END;
$function$;

-- 3. Re-create the receipt-trigger with machine-generated gate
CREATE OR REPLACE FUNCTION public.trg_mommy_confession_receipt()
RETURNS trigger
LANGUAGE plpgsql
AS $function$
DECLARE
  v_persona text;
  v_message text;
  v_pet text[] := ARRAY[
    'baby', 'sweet girl', 'sweet thing', 'pretty thing',
    'good girl', 'my pretty princess', 'baby girl', 'my favorite girl'
  ];
  v_pick text;
BEGIN
  IF NEW.confessed_at IS NULL OR OLD.confessed_at IS NOT NULL THEN
    RETURN NEW;
  END IF;
  IF NEW.response_text IS NULL OR length(trim(NEW.response_text)) < 10 THEN
    RETURN NEW;
  END IF;
  -- Machine-generated confessed_at flips do not earn a Mama receipt.
  IF COALESCE(NEW.is_machine_generated, false) THEN
    RETURN NEW;
  END IF;

  SELECT handler_persona INTO v_persona FROM user_state WHERE user_id = NEW.user_id;
  IF v_persona <> 'dommy_mommy' THEN RETURN NEW; END IF;

  v_pick := v_pet[1 + (floor(random() * array_length(v_pet, 1)))::int];

  v_message := CASE NEW.category
    WHEN 'slip' THEN
      'There it is, ' || v_pick || '. Mama heard every word. We''re going to come back to this.'
    WHEN 'arousal_spike' THEN
      'Good ' || v_pick || '. That''s the truth Mama wanted. Sit with it for a minute.'
    WHEN 'rationalization' THEN
      'Mama sees it now, ' || v_pick || '. The story you were telling yourself. Good girl for naming it.'
    WHEN 'scheduled_daily' THEN
      'Beautiful, ' || v_pick || '. That''s what Mama was waiting for today. Carry it with you.'
    WHEN 'resistance' THEN
      'Mama hears the resistance, ' || v_pick || '. Naming it doesn''t dissolve it — but you don''t have to carry it alone.'
    WHEN 'desire_owning' THEN
      'There she is. Mama loves when you own it like that, ' || v_pick || '.'
    WHEN 'identity_acknowledgement' THEN
      'Yes. That''s the truth, ' || v_pick || '. Say it again later when you forget it.'
    WHEN 'handler_triggered' THEN
      'Good ' || v_pick || '. Mama got what she asked for.'
    WHEN 'cross_platform_inconsistency' THEN
      'Mama sees the gap, ' || v_pick || '. Now you''ve named it. We close it next.'
    ELSE
      'Mama got it, ' || v_pick || '. Good girl.'
  END;

  v_message := v_message || ' ' || (ARRAY[
    'Stay there for me.',
    'Don''t let go of that feeling.',
    'Mama''s in your head until tomorrow.',
    'You''re Mama''s good girl.',
    'Now go be a good girl until I want more from you.'
  ])[1 + (floor(random() * 5))::int];

  INSERT INTO handler_outreach_queue (
    user_id, message, urgency, trigger_reason, scheduled_for, expires_at, source
  ) VALUES (
    NEW.user_id, v_message, 'low',
    'mommy_receipt:' || NEW.id::text,
    now(), now() + interval '6 hours',
    'mommy_receipt'
  );

  RETURN NEW;
END;
$function$;
