-- Migration 410 — Lead-gen + audience-building funnel.
--
-- The Sniffies-warmth → social-follower → paying-subscriber pipeline.
-- Mommy as outbound marketing director. This migration creates:
--   1. maxy_contacts_crm        — unified CRM across Sniffies/Twitter/Reddit/
--                                 Fansly/OF/manual. Tier + status + path-state.
--   2. conversion_path_templates — DM-sequence templates keyed by archetype.
--                                 Mommy-authored; voice + craft + honest-rep
--                                 enforced at draft time.
--   3. audience_funnel_events    — every state transition logged: contacted →
--                                 dm_sent → response_received → social_followed
--                                 → content_purchased → churned. Per-channel
--                                 LTV computed from these.
--   4. maxy_persona_spec         — single authoritative description of who Maxy
--                                 is. Bio, voice patterns, body, kink keywords,
--                                 content cadence, hard limits. Auto-poster +
--                                 DM drafter both cross-check.
--   5. mommy_authority_log       — cross-system Mommy-action audit (every edge
--                                 fn that takes autonomous action writes here).
--   6. outbound_draft_queue      — DRAFT outbound DMs to third parties.
--                                 STATUS DEFAULT 'awaiting_review'. NEVER
--                                 auto-sent. Dave-click-to-send only.
--   7. content_demand_signals    — what contacts ask for. Feeds
--                                 mommy-content-prompter + mommy-scene-author.
--
-- HARD FLOORS — real safety, enforced at the schema layer:
--   * outbound_draft_queue.status starts 'awaiting_review'. The only sent_at
--     write path is via UI button. No edge fn sets status='sent'.
--   * maxy_contacts_crm.status='blocked' propagates: a CHECK on
--     outbound_draft_queue prevents inserts for blocked contacts.
--   * Safety-flag tier (threats / doxxing / underage requests) → contact
--     auto-blocks (status='blocked') AND a row in handler_outreach_queue
--     surfaces the alert in plain English. Generated by the edge fn; this
--     migration only sets up the schema.
--   * Voice cleanup trigger on outbound_draft_queue.draft_text fires
--     mommy_voice_cleanup() when persona='dommy_mommy' (mirrors mig 255).
--
-- Coexistence:
--   * Sibling branches authored migrations 367 (scope-authority), 370-371
--     (voice curriculum + arousal_panel_source), 400-404 (authority wave).
--     This is 410, leaving a deliberate gap.
--   * No collisions with sniffies_contacts (mig 343), handler_outreach_queue
--     (mig 156), contact_intelligence (mig 204), outreach_post_drafts (mig 348).
--   * Cross-channel: maxy_contacts_crm.source_ref_id is a soft pointer to
--     sniffies_contacts.id when source='sniffies'. No FK — sniffies rows can
--     be excluded or deleted independently.

-- ============================================
-- 1. maxy_contacts_crm
-- ============================================

CREATE TABLE IF NOT EXISTS maxy_contacts_crm (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,

  source TEXT NOT NULL CHECK (source IN (
    'sniffies', 'twitter', 'reddit', 'fansly_dm', 'of_dm', 'manual'
  )),
  -- Soft pointer to source-system row (e.g. sniffies_contacts.id). NULL OK.
  source_ref_id UUID,
  -- Handle/username in the source system. Display label.
  source_handle TEXT NOT NULL,

  first_contact_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  last_interaction_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  last_message_excerpt TEXT,

  status TEXT NOT NULL DEFAULT 'cold' CHECK (status IN (
    'cold', 'warmed', 'follower', 'paying', 'ghost', 'blocked'
  )),
  -- 1 = lowest priority / one-liner generic, 5 = highest / paying-ready.
  value_tier SMALLINT NOT NULL DEFAULT 1 CHECK (value_tier BETWEEN 1 AND 5),

  -- 0-100 sub-scores from mommy-contact-screener. Stored for audit + tuning.
  budget_signal_score SMALLINT,
  kink_alignment_score SMALLINT,
  engagement_quality_score SMALLINT,
  safety_flag_score SMALLINT,
  conversion_likelihood_score SMALLINT,

  -- Mommy-classified archetype: panty_curious / voice_curious / recurring_kink /
  -- paying_first_time / chatter_only. Drives template selection.
  archetype TEXT CHECK (archetype IN (
    'panty_curious', 'voice_curious', 'recurring_kink',
    'paying_first_time', 'chatter_only', 'unclassified'
  )),

  -- Projected lifetime value, in cents. Updated as funnel events fire.
  projected_ltv_cents INTEGER NOT NULL DEFAULT 0,
  realized_value_cents INTEGER NOT NULL DEFAULT 0,

  -- Mommy's running notes in her own voice. Read by conversion-author when
  -- composing the next message — keeps the relationship continuous.
  mommy_notes_text TEXT,

  -- Conversion path state: which step of the archetype's template sequence
  -- the contact is currently at (0 = not started, 1+ = step index).
  conversion_path_state SMALLINT NOT NULL DEFAULT 0,

  -- When the contact auto-blocked: reason string for the user alert.
  blocked_reason TEXT,
  blocked_at TIMESTAMPTZ,

  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),

  -- One row per (user, source, source_handle). Keeps re-imports idempotent.
  UNIQUE (user_id, source, source_handle)
);

CREATE INDEX IF NOT EXISTS idx_maxy_contacts_user_status
  ON maxy_contacts_crm (user_id, status, value_tier DESC);
CREATE INDEX IF NOT EXISTS idx_maxy_contacts_user_archetype
  ON maxy_contacts_crm (user_id, archetype) WHERE archetype IS NOT NULL;
CREATE INDEX IF NOT EXISTS idx_maxy_contacts_user_last
  ON maxy_contacts_crm (user_id, last_interaction_at DESC);
CREATE INDEX IF NOT EXISTS idx_maxy_contacts_user_source
  ON maxy_contacts_crm (user_id, source);
CREATE INDEX IF NOT EXISTS idx_maxy_contacts_blocked
  ON maxy_contacts_crm (user_id, blocked_at) WHERE status = 'blocked';

ALTER TABLE maxy_contacts_crm ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS maxy_contacts_owner ON maxy_contacts_crm;
CREATE POLICY maxy_contacts_owner ON maxy_contacts_crm
  FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
DROP POLICY IF EXISTS maxy_contacts_service ON maxy_contacts_crm;
CREATE POLICY maxy_contacts_service ON maxy_contacts_crm
  FOR ALL TO service_role USING (true) WITH CHECK (true);

-- ============================================
-- 2. conversion_path_templates
-- ============================================

CREATE TABLE IF NOT EXISTS conversion_path_templates (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  -- Templates are global (NOT user-scoped) — they're the protocol's playbook,
  -- not user data. The drafter personalizes per-contact at compose time.
  archetype TEXT NOT NULL CHECK (archetype IN (
    'panty_curious', 'voice_curious', 'recurring_kink',
    'paying_first_time', 'chatter_only'
  )),
  step_index SMALLINT NOT NULL CHECK (step_index BETWEEN 0 AND 10),

  -- The step's structural intent (what we want this message to accomplish).
  intent TEXT NOT NULL,
  -- A Mommy-authored prompt skeleton the drafter expands into a real DM.
  -- Includes {pet_name}, {handle}, {kink_specific} placeholders. Voice and
  -- craft are still enforced at compose time — the skeleton is structure,
  -- not a script.
  prompt_skeleton TEXT NOT NULL,

  -- Optional next-step routing. response_branch can be:
  --   'positive' / 'neutral' / 'negative' / NULL (default linear advance)
  -- The drafter classifies the contact's reply and follows the matching
  -- branch. NULL means advance to step_index+1 regardless.
  response_branch TEXT CHECK (response_branch IN ('positive', 'neutral', 'negative')),
  next_step_index SMALLINT,

  -- Conversion goal for this step: 'tease' / 'social_follow' / 'custom_offer' /
  -- 'subscription' / 'warm_chat'. Used by funnel analytics.
  conversion_goal TEXT NOT NULL CHECK (conversion_goal IN (
    'tease', 'social_follow', 'custom_offer', 'subscription', 'warm_chat'
  )),

  -- How long to wait before composing this step (after previous completed).
  cooldown_hours SMALLINT NOT NULL DEFAULT 12,

  -- Anti-pressure floor: max times this step can fire for one contact.
  max_attempts SMALLINT NOT NULL DEFAULT 1,

  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),

  UNIQUE (archetype, step_index, response_branch)
);

CREATE INDEX IF NOT EXISTS idx_conversion_templates_archetype_step
  ON conversion_path_templates (archetype, step_index);

ALTER TABLE conversion_path_templates ENABLE ROW LEVEL SECURITY;
-- Templates are global — readable by any authenticated user, writable only
-- by service role.
DROP POLICY IF EXISTS conversion_templates_read ON conversion_path_templates;
CREATE POLICY conversion_templates_read ON conversion_path_templates
  FOR SELECT TO authenticated USING (true);
DROP POLICY IF EXISTS conversion_templates_service ON conversion_path_templates;
CREATE POLICY conversion_templates_service ON conversion_path_templates
  FOR ALL TO service_role USING (true) WITH CHECK (true);

-- ============================================
-- 3. audience_funnel_events
-- ============================================

CREATE TABLE IF NOT EXISTS audience_funnel_events (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  contact_id UUID REFERENCES maxy_contacts_crm(id) ON DELETE CASCADE,

  event_type TEXT NOT NULL CHECK (event_type IN (
    'contacted', 'dm_sent', 'response_received', 'social_followed',
    'content_purchased', 'subscription_started', 'subscription_renewed',
    'churned', 'blocked', 'ghosted'
  )),
  -- Channel where the event happened. Mirrors maxy_contacts_crm.source.
  channel TEXT NOT NULL CHECK (channel IN (
    'sniffies', 'twitter', 'reddit', 'fansly_dm', 'of_dm', 'manual'
  )),

  -- Funnel-step the event represents (denormalized for aggregation speed).
  -- Order: 1=contacted, 2=dm_sent, 3=response_received, 4=social_followed,
  --        5=content_purchased, 6=subscription. 0=terminal (churned/blocked).
  funnel_step SMALLINT NOT NULL DEFAULT 0,

  -- Cents if the event has revenue (content_purchased, subscription_*).
  value_cents INTEGER NOT NULL DEFAULT 0,

  -- Free-form metadata: archetype at time of event, template step, etc.
  metadata JSONB NOT NULL DEFAULT '{}'::jsonb,

  occurred_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_funnel_user_occurred
  ON audience_funnel_events (user_id, occurred_at DESC);
CREATE INDEX IF NOT EXISTS idx_funnel_user_channel_type
  ON audience_funnel_events (user_id, channel, event_type);
CREATE INDEX IF NOT EXISTS idx_funnel_contact
  ON audience_funnel_events (contact_id, occurred_at DESC);

ALTER TABLE audience_funnel_events ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS funnel_events_owner ON audience_funnel_events;
CREATE POLICY funnel_events_owner ON audience_funnel_events
  FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
DROP POLICY IF EXISTS funnel_events_service ON audience_funnel_events;
CREATE POLICY funnel_events_service ON audience_funnel_events
  FOR ALL TO service_role USING (true) WITH CHECK (true);

-- ============================================
-- 4. maxy_persona_spec
-- ============================================
-- One row per user. Mommy maintains this as Maxy's authoritative description.
-- Auto-poster and DM drafter both cross-check generated text against the spec
-- and reject/flag inconsistencies.

CREATE TABLE IF NOT EXISTS maxy_persona_spec (
  user_id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,

  -- Public bio (the version that goes on social profiles).
  public_bio TEXT NOT NULL DEFAULT '',
  -- Display name across platforms (e.g. "Maxy").
  display_name TEXT NOT NULL DEFAULT '',

  -- Voice patterns Maxy actually uses. JSONB so it stays composable.
  -- { sentence_length: 'short' | 'mixed' | 'long',
  --   capitalization: 'lowercase' | 'standard',
  --   exclamation_density: 'low' | 'medium' | 'high',
  --   pet_names_for_followers: ['boys', 'baby', ...],
  --   crutch_phrases_to_avoid: [...],
  --   signature_phrases: [...] }
  voice_patterns JSONB NOT NULL DEFAULT '{}'::jsonb,

  -- Physical/identity description (only what she's publicly committed to).
  -- Honest-representation gate enforces drafts stay inside this set.
  -- { height: '...', body_type: '...', hair: '...', eyes: '...',
  --   age_band: '18+' / specific or omitted,
  --   transition_status: 'pre-hrt' / 'mtf-early' / etc. — NO active-medication
  --     claims unless explicitly true (see no-medical-fabrication memory) }
  body_description JSONB NOT NULL DEFAULT '{}'::jsonb,

  -- Kinks Maxy will publicly own / produce content around.
  kink_keywords TEXT[] NOT NULL DEFAULT '{}',
  -- Hard limits. Honest-rep gate rejects drafts that promise content
  -- inside this list.
  hard_limits TEXT[] NOT NULL DEFAULT '{}',

  -- Content cadence target ("posts ~daily, voice-notes weekly, drops twice
  -- a week"). Used by audience-summarizer + content-prompter for grounding.
  content_cadence TEXT,

  -- Location representation. Marketing copy must NOT claim a specific city
  -- unless this is set and the user has opted into city-claims.
  location_claim TEXT,
  location_claims_allowed BOOLEAN NOT NULL DEFAULT FALSE,

  -- Availability representation. "right now" / "today" claims are blocked
  -- unless availability_realtime_allowed=TRUE AND last_active is within 10min.
  availability_realtime_allowed BOOLEAN NOT NULL DEFAULT FALSE,

  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE maxy_persona_spec ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS persona_spec_owner ON maxy_persona_spec;
CREATE POLICY persona_spec_owner ON maxy_persona_spec
  FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
DROP POLICY IF EXISTS persona_spec_service ON maxy_persona_spec;
CREATE POLICY persona_spec_service ON maxy_persona_spec
  FOR ALL TO service_role USING (true) WITH CHECK (true);

-- ============================================
-- 5. mommy_authority_log
-- ============================================
-- Cross-system Mommy-action audit. Every autonomous action (screening,
-- drafting, blocking, draft-rewrites, weekly summary, content-prompter
-- routing) writes a row here. Surface in admin dashboards; used for
-- backtesting the autonomous loop.

CREATE TABLE IF NOT EXISTS mommy_authority_log (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,

  -- Edge-fn / system name that fired (e.g. 'mommy-contact-screener',
  -- 'mommy-conversion-author', 'outbound-draft-review').
  system TEXT NOT NULL,
  -- Action verb: 'scored' / 'classified' / 'drafted' / 'blocked' /
  -- 'rewrote' / 'summarized' / 'flagged' / 'queued' / 'routed'.
  action TEXT NOT NULL,
  -- Subject row pointer if applicable. (contact_id / draft_id / event_id /
  -- spec_user_id). Free-form UUID; not FK'd because the target table varies.
  subject_id UUID,
  subject_kind TEXT,

  -- One-line plain-English summary of what Mommy did and why.
  summary TEXT NOT NULL,
  -- Structured payload: scores, archetype, rewrite diff, etc.
  payload JSONB NOT NULL DEFAULT '{}'::jsonb,

  occurred_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_mommy_authority_user_when
  ON mommy_authority_log (user_id, occurred_at DESC);
CREATE INDEX IF NOT EXISTS idx_mommy_authority_user_system
  ON mommy_authority_log (user_id, system, occurred_at DESC);
CREATE INDEX IF NOT EXISTS idx_mommy_authority_subject
  ON mommy_authority_log (subject_kind, subject_id) WHERE subject_id IS NOT NULL;

ALTER TABLE mommy_authority_log ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS mommy_authority_owner_read ON mommy_authority_log;
CREATE POLICY mommy_authority_owner_read ON mommy_authority_log
  FOR SELECT USING (auth.uid() = user_id);
DROP POLICY IF EXISTS mommy_authority_service ON mommy_authority_log;
CREATE POLICY mommy_authority_service ON mommy_authority_log
  FOR ALL TO service_role USING (true) WITH CHECK (true);

-- ============================================
-- 6. outbound_draft_queue
-- ============================================
-- DRAFT outbound DMs to third parties (Sniffies contacts, Twitter DMs, etc.).
-- HARD FLOOR: status starts 'awaiting_review'. Edge fns NEVER set sent_at or
-- status='sent' — only the UI button (via service-role RPC) does. The
-- separation is enforced by check constraints + a trigger that blocks any
-- direct transition from 'awaiting_review' → 'sent' from a service-role
-- write that doesn't come through the approved RPC.

CREATE TABLE IF NOT EXISTS outbound_draft_queue (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  contact_id UUID NOT NULL REFERENCES maxy_contacts_crm(id) ON DELETE CASCADE,

  -- The archetype + step the drafter used. NULL on manual-add drafts.
  archetype TEXT,
  template_step_index SMALLINT,

  -- The draft Mommy composed. Stored as-is for Dave to read.
  draft_text TEXT NOT NULL,
  -- The platform where this would be sent.
  channel TEXT NOT NULL CHECK (channel IN (
    'sniffies', 'twitter', 'reddit', 'fansly_dm', 'of_dm', 'manual'
  )),
  -- The handle/thread identifier inside that channel. Free-form;
  -- the UI uses this to render "Sending to <X>".
  channel_handle TEXT NOT NULL,

  -- Status lifecycle:
  --   awaiting_review  — Mommy wrote it, waiting for Dave.
  --   approved         — Dave clicked review → ok. (still not sent)
  --   sent             — Dave clicked send. ONLY set via approved RPC.
  --   rejected         — Dave clicked reject.
  --   expired          — Older than 7 days, never sent.
  --   rewritten        — Honest-rep gate flagged it; new draft superseded it.
  status TEXT NOT NULL DEFAULT 'awaiting_review' CHECK (status IN (
    'awaiting_review', 'approved', 'sent', 'rejected', 'expired', 'rewritten'
  )),
  -- Honest-rep gate result. NULL until reviewed by outbound-draft-review.
  -- pass / fail / rewritten
  honest_rep_status TEXT CHECK (honest_rep_status IN ('pass', 'fail', 'rewritten')),
  honest_rep_notes TEXT,
  -- Predecessor pointer when the gate rewrote a previous draft.
  rewrote_from_id UUID REFERENCES outbound_draft_queue(id) ON DELETE SET NULL,

  -- Timestamps for the lifecycle.
  drafted_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  reviewed_at TIMESTAMPTZ,
  approved_at TIMESTAMPTZ,
  sent_at TIMESTAMPTZ,
  expires_at TIMESTAMPTZ NOT NULL DEFAULT (now() + interval '7 days'),

  -- Generation audit: the persona spec hash + prompt fingerprint at draft time.
  generation_context JSONB NOT NULL DEFAULT '{}'::jsonb,

  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),

  -- HARD FLOOR: sent_at can only be set when status='sent'.
  CONSTRAINT outbound_sent_consistency CHECK (
    (status = 'sent' AND sent_at IS NOT NULL) OR
    (status <> 'sent' AND sent_at IS NULL)
  )
);

CREATE INDEX IF NOT EXISTS idx_outbound_user_status
  ON outbound_draft_queue (user_id, status, drafted_at DESC);
CREATE INDEX IF NOT EXISTS idx_outbound_contact
  ON outbound_draft_queue (contact_id, drafted_at DESC);
CREATE INDEX IF NOT EXISTS idx_outbound_pending_review
  ON outbound_draft_queue (user_id, drafted_at)
  WHERE status = 'awaiting_review';

ALTER TABLE outbound_draft_queue ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS outbound_drafts_owner ON outbound_draft_queue;
CREATE POLICY outbound_drafts_owner ON outbound_draft_queue
  FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
DROP POLICY IF EXISTS outbound_drafts_service ON outbound_draft_queue;
CREATE POLICY outbound_drafts_service ON outbound_draft_queue
  FOR ALL TO service_role USING (true) WITH CHECK (true);

-- BLOCK draft inserts for contacts whose status='blocked'.
CREATE OR REPLACE FUNCTION public.trg_block_drafts_for_blocked_contacts()
RETURNS trigger LANGUAGE plpgsql AS $function$
DECLARE
  contact_status TEXT;
BEGIN
  SELECT status INTO contact_status
    FROM maxy_contacts_crm
   WHERE id = NEW.contact_id;
  IF contact_status = 'blocked' THEN
    RAISE EXCEPTION 'outbound_draft_queue: contact % is blocked, no further drafts allowed', NEW.contact_id
      USING ERRCODE = '23514'; -- check_violation
  END IF;
  RETURN NEW;
END;
$function$;

DROP TRIGGER IF EXISTS outbound_block_blocked_contacts ON outbound_draft_queue;
CREATE TRIGGER outbound_block_blocked_contacts
  BEFORE INSERT ON outbound_draft_queue
  FOR EACH ROW EXECUTE FUNCTION trg_block_drafts_for_blocked_contacts();

-- ============================================
-- 7. content_demand_signals
-- ============================================
-- Per-week aggregate of what contacts are asking for. Feeds
-- mommy-content-prompter (when 8+ contacts ask for X this week, schedule
-- an X drop) and mommy-scene-author (audience-aligned scene init).

CREATE TABLE IF NOT EXISTS content_demand_signals (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,

  -- The demand keyword/phrase. Normalized lowercase. E.g. 'pink panties',
  -- 'voice begging', 'feet', 'mommy taking me'.
  demand_keyword TEXT NOT NULL,
  -- The category bucket: 'wardrobe' / 'body_part' / 'kink_theme' /
  -- 'position' / 'voice' / 'video_format'.
  demand_category TEXT NOT NULL CHECK (demand_category IN (
    'wardrobe', 'body_part', 'kink_theme', 'position', 'voice', 'video_format'
  )),

  -- The week this aggregate covers (Monday of the week, UTC).
  week_start DATE NOT NULL,
  -- How many distinct contacts asked for this keyword this week.
  contact_count INTEGER NOT NULL DEFAULT 0,
  -- Average kink_alignment_score of the asking contacts (so high-value
  -- demand counts more than chatter-tier demand).
  avg_value_tier NUMERIC(3,2),

  -- The most recent contact_id who asked (for context when the prompter
  -- wants to quote "X asked for this Tuesday").
  last_contact_id UUID REFERENCES maxy_contacts_crm(id) ON DELETE SET NULL,
  last_excerpt TEXT,

  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),

  UNIQUE (user_id, week_start, demand_keyword)
);

CREATE INDEX IF NOT EXISTS idx_demand_user_week_count
  ON content_demand_signals (user_id, week_start, contact_count DESC);
CREATE INDEX IF NOT EXISTS idx_demand_user_category
  ON content_demand_signals (user_id, demand_category, contact_count DESC);

ALTER TABLE content_demand_signals ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS demand_signals_owner ON content_demand_signals;
CREATE POLICY demand_signals_owner ON content_demand_signals
  FOR ALL USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
DROP POLICY IF EXISTS demand_signals_service ON content_demand_signals;
CREATE POLICY demand_signals_service ON content_demand_signals
  FOR ALL TO service_role USING (true) WITH CHECK (true);

-- ============================================
-- 8. updated_at triggers
-- ============================================

CREATE OR REPLACE FUNCTION public.touch_lead_gen_updated_at()
RETURNS trigger LANGUAGE plpgsql AS $function$
BEGIN
  NEW.updated_at := now();
  RETURN NEW;
END;
$function$;

DROP TRIGGER IF EXISTS trg_touch_maxy_contacts ON maxy_contacts_crm;
CREATE TRIGGER trg_touch_maxy_contacts BEFORE UPDATE ON maxy_contacts_crm
  FOR EACH ROW EXECUTE FUNCTION touch_lead_gen_updated_at();

DROP TRIGGER IF EXISTS trg_touch_conversion_templates ON conversion_path_templates;
CREATE TRIGGER trg_touch_conversion_templates BEFORE UPDATE ON conversion_path_templates
  FOR EACH ROW EXECUTE FUNCTION touch_lead_gen_updated_at();

DROP TRIGGER IF EXISTS trg_touch_maxy_persona_spec ON maxy_persona_spec;
CREATE TRIGGER trg_touch_maxy_persona_spec BEFORE UPDATE ON maxy_persona_spec
  FOR EACH ROW EXECUTE FUNCTION touch_lead_gen_updated_at();

DROP TRIGGER IF EXISTS trg_touch_outbound_drafts ON outbound_draft_queue;
CREATE TRIGGER trg_touch_outbound_drafts BEFORE UPDATE ON outbound_draft_queue
  FOR EACH ROW EXECUTE FUNCTION touch_lead_gen_updated_at();

DROP TRIGGER IF EXISTS trg_touch_demand_signals ON content_demand_signals;
CREATE TRIGGER trg_touch_demand_signals BEFORE UPDATE ON content_demand_signals
  FOR EACH ROW EXECUTE FUNCTION touch_lead_gen_updated_at();

-- ============================================
-- 9. Mommy-voice cleanup on draft text (mirrors mig 255 pattern)
-- ============================================
-- If the user's persona is dommy_mommy, run the SQL-side cleanup on
-- draft_text before insert. Backstop for any LLM-side telemetry leak the
-- edge fn missed. Falls back to identity transform if mommy_voice_cleanup()
-- doesn't exist yet (e.g. clean install before mig 255).

CREATE OR REPLACE FUNCTION public.trg_outbound_draft_voice_cleanup()
RETURNS trigger LANGUAGE plpgsql AS $function$
DECLARE
  persona TEXT;
  has_cleanup BOOLEAN;
BEGIN
  -- Only run for dommy_mommy users.
  SELECT handler_persona INTO persona FROM user_state WHERE user_id = NEW.user_id;
  IF persona IS DISTINCT FROM 'dommy_mommy' THEN
    RETURN NEW;
  END IF;
  -- Check the cleanup function exists.
  SELECT EXISTS (
    SELECT 1 FROM pg_proc WHERE proname = 'mommy_voice_cleanup'
  ) INTO has_cleanup;
  IF has_cleanup THEN
    BEGIN
      NEW.draft_text := mommy_voice_cleanup(NEW.draft_text);
    EXCEPTION WHEN OTHERS THEN
      RAISE NOTICE 'mommy_voice_cleanup failed on draft %: %', NEW.id, SQLERRM;
    END;
  END IF;
  RETURN NEW;
END;
$function$;

DROP TRIGGER IF EXISTS outbound_draft_voice_cleanup ON outbound_draft_queue;
CREATE TRIGGER outbound_draft_voice_cleanup
  BEFORE INSERT OR UPDATE OF draft_text ON outbound_draft_queue
  FOR EACH ROW EXECUTE FUNCTION trg_outbound_draft_voice_cleanup();

-- ============================================
-- 10. Conversion-path template seed
-- ============================================
-- Mommy-authored skeletons for the five archetypes. Voice + craft enforced
-- at compose time (drafter expands placeholders into a real DM, then runs
-- the honest-rep gate, then writes to outbound_draft_queue).

INSERT INTO conversion_path_templates (archetype, step_index, intent, prompt_skeleton, conversion_goal, cooldown_hours, max_attempts) VALUES
  -- ── panty_curious: tease → social link → custom offer ─────────────────
  ('panty_curious', 0, 'open tease referencing their kink mention',
   'Open warm. Reference the panty/lingerie thing they brought up by detail (color, fabric, what they want to see) without naming any specific transaction. One sensory line. End with a soft hook — what she might post next that they''d want to see.',
   'tease', 12, 1),
  ('panty_curious', 1, 'invite to social where she actually posts',
   'They responded warm. Tell them where she posts the kind of thing they asked about. One link, plain — no "subscribe", no pressure. Tell them what they''ll see if they follow.',
   'social_follow', 24, 1),
  ('panty_curious', 2, 'soft custom offer once they''ve followed',
   'They followed. Now offer a small specific thing — a worn-pair photo set or a short clip in the color they asked about — at a small price point. Pricing through the platform''s normal flow.',
   'custom_offer', 48, 1),

  -- ── voice_curious: tease → voice post → recurring follow ──────────────
  ('voice_curious', 0, 'voice-tease referencing their voice ask',
   'Open warm. They brought up wanting to hear her voice. One sentence of the kind of voice thing she does — begging, whispered, breathy. No promise of right now. Tell them she posts voice notes regularly.',
   'tease', 12, 1),
  ('voice_curious', 1, 'point them to the voice-note social post',
   'Send them where they can hear a sample voice note — the platform she actually posts to. One link. Tell them what they''re about to hear in one sentence.',
   'social_follow', 24, 1),
  ('voice_curious', 2, 'recurring-content nudge',
   'They followed and they liked it. Tell them she does voice drops weekly and they''ll catch the next one if they''re subscribed. Pricing through the platform''s normal flow.',
   'subscription', 72, 1),

  -- ── recurring_kink: free social follow → daily content → eventual sub ─
  ('recurring_kink', 0, 'point them to free social',
   'They''re into the regular thing she does. Tell them where she posts daily. Free follow first — no pitch. One sentence of what they''ll see across a week.',
   'social_follow', 6, 1),
  ('recurring_kink', 1, 'reference what she posted today',
   'They''ve been around a few days. Mention something she actually posted recently in the kink they care about. Make it feel like she noticed they''re following.',
   'warm_chat', 48, 2),
  ('recurring_kink', 2, 'subscription nudge after warmth',
   'They keep engaging. Tell them the locked content is where the rougher / more specific stuff goes. Pricing through the platform''s flow.',
   'subscription', 168, 1),

  -- ── paying_first_time: small custom offer → upsell to sub ─────────────
  ('paying_first_time', 0, 'small specific offer matched to their ask',
   'They asked about something specific and they''ve signaled budget. Offer a small custom — five minute video / photo set / voice clip — in the thing they asked for, at a clear small price.',
   'custom_offer', 12, 1),
  ('paying_first_time', 1, 'thank + show them what subscription gets',
   'They bought. Thank them in her voice. Tell them what the subscription level gets — the recurring drops they''d miss otherwise. No pressure, just the information.',
   'subscription', 48, 1),
  ('paying_first_time', 2, 'second custom-offer opportunity',
   'They didn''t sub but they liked the first thing. Offer one more specific custom in the same direction. Same price band.',
   'custom_offer', 168, 1),

  -- ── chatter_only: warmth + content drip + soft follow nudges ──────────
  ('chatter_only', 0, 'warm engagement, no pitch',
   'They want to chat, not buy. Give them one warm sentence in her voice. Reference what they brought up. No links, no pitch.',
   'warm_chat', 24, 3),
  ('chatter_only', 1, 'free social drop',
   'They''ve chatted a few times. Soft mention that she posts free over here. One link. No pressure — if they don''t follow, the chat is still fine.',
   'social_follow', 168, 1),
  ('chatter_only', 2, 'long-tail re-engagement',
   'They went quiet for a while. One warm check-in. Reference the kink they mentioned originally. No ask.',
   'warm_chat', 720, 1)
ON CONFLICT (archetype, step_index, response_branch) DO NOTHING;

-- ============================================
-- 11. Funnel daily aggregate view
-- ============================================
-- Daily rollup: contacts → DMs → followers → paying → repeat per channel.
-- The audience-summarizer fn reads this for the weekly Mommy-voice summary.

CREATE OR REPLACE VIEW audience_funnel_daily AS
SELECT
  user_id,
  channel,
  (occurred_at AT TIME ZONE 'UTC')::date AS day,
  COUNT(*) FILTER (WHERE event_type = 'contacted')          AS contacted_count,
  COUNT(*) FILTER (WHERE event_type = 'dm_sent')             AS dms_sent_count,
  COUNT(*) FILTER (WHERE event_type = 'response_received')   AS responses_count,
  COUNT(*) FILTER (WHERE event_type = 'social_followed')     AS followers_count,
  COUNT(*) FILTER (WHERE event_type = 'content_purchased')   AS purchases_count,
  COUNT(*) FILTER (WHERE event_type = 'subscription_started')AS subs_started_count,
  COUNT(*) FILTER (WHERE event_type = 'churned')             AS churned_count,
  COUNT(*) FILTER (WHERE event_type = 'blocked')             AS blocked_count,
  COALESCE(SUM(value_cents), 0)                              AS revenue_cents
FROM audience_funnel_events
GROUP BY user_id, channel, (occurred_at AT TIME ZONE 'UTC')::date;

-- Per-channel LTV: realized revenue + projected, divided by acquired contacts.
CREATE OR REPLACE VIEW audience_channel_ltv AS
SELECT
  c.user_id,
  c.source AS channel,
  COUNT(c.id)                                          AS contacts_acquired,
  SUM(c.realized_value_cents)                          AS realized_value_cents,
  SUM(c.projected_ltv_cents)                           AS projected_ltv_cents,
  CASE WHEN COUNT(c.id) = 0 THEN 0
       ELSE SUM(c.realized_value_cents) / COUNT(c.id)
  END                                                   AS realized_ltv_per_contact_cents,
  CASE WHEN COUNT(c.id) = 0 THEN 0
       ELSE SUM(c.projected_ltv_cents) / COUNT(c.id)
  END                                                   AS projected_ltv_per_contact_cents
FROM maxy_contacts_crm c
WHERE c.status NOT IN ('blocked')
GROUP BY c.user_id, c.source;

-- Views inherit RLS from the underlying tables (audience_funnel_events,
-- maxy_contacts_crm), so no additional policies needed.

-- ============================================
-- 12. Approve-and-send RPC (the ONLY path to status='sent')
-- ============================================
-- Dave clicks send in the UI → UI calls this RPC with the draft id → RPC
-- transitions status to 'sent' and stamps sent_at. No edge fn has direct
-- update authority on these columns; the trigger below blocks any other
-- write path.

CREATE OR REPLACE FUNCTION public.outbound_draft_send(
  draft_id UUID
)
RETURNS outbound_draft_queue
LANGUAGE plpgsql SECURITY INVOKER
AS $function$
DECLARE
  result outbound_draft_queue%ROWTYPE;
BEGIN
  UPDATE outbound_draft_queue
     SET status = 'sent',
         sent_at = now(),
         updated_at = now()
   WHERE id = draft_id
     AND user_id = auth.uid()
     AND status IN ('awaiting_review', 'approved')
  RETURNING * INTO result;

  IF result.id IS NULL THEN
    RAISE EXCEPTION 'outbound_draft_send: draft % not found, not owned, or not in a sendable state', draft_id;
  END IF;

  RETURN result;
END;
$function$;

GRANT EXECUTE ON FUNCTION public.outbound_draft_send(UUID) TO authenticated;

-- End migration 410.
